# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("symbol", models.CharField(default="₦", max_length=5)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="Exchange rate relative to company base currency",
                        max_digits=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=20, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="TaxGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sequence", models.PositiveIntegerField(default=10)),
            ],
            options={
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="UomCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "UOM Category",
                "verbose_name_plural": "UOM Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/logos/"
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=255)),
                ("street2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="TIN / VAT number", max_length=100
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="erp_base.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTermLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("balance", "Balance"),
                            ("percent", "Percent"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="balance",
                        max_length=10,
                    ),
                ),
                (
                    "value_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("days", models.PositiveIntegerField(default=0)),
                (
                    "payment_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_base.paymentterm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "complete_name",
                    models.CharField(blank=True, editable=False, max_length=512),
                ),
                (
                    "costing_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Price"),
                            ("avco", "Average Cost (AVCO)"),
                            ("fifo", "First In First Out (FIFO)"),
                        ],
                        default="avco",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="erp_base.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product categories",
                "ordering": ["complete_name"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type_tax_use",
                    models.CharField(
                        choices=[
                            ("sale", "Sales"),
                            ("purchase", "Purchases"),
                            ("none", "None"),
                        ],
                        default="sale",
                        max_length=10,
                    ),
                ),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("division", "% of Price Tax Included"),
                        ],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Tax rate as a percentage (e.g. 7.5 for 7.5%)",
                        max_digits=10,
                    ),
                ),
                ("include_base_amount", models.BooleanField(default=False)),
                ("is_base_affected", models.BooleanField(default=True)),
                (
                    "price_include",
                    models.BooleanField(
                        default=False, help_text="Tax included in price"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tax_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxes",
                        to="erp_base.taxgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "uom_type",
                    models.CharField(
                        choices=[
                            ("reference", "Reference Unit"),
                            ("smaller", "Smaller than reference"),
                            ("bigger", "Bigger than reference"),
                        ],
                        default="reference",
                        max_length=10,
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="How many of this UOM equals the reference UOM",
                        max_digits=20,
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.01"), max_digits=10
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uoms",
                        to="erp_base.uomcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact"),
                            ("company", "Company"),
                            ("individual", "Individual"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("is_customer", models.BooleanField(default=True)),
                ("is_vendor", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("street2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partners",
                        to="erp_base.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partners",
                        to="erp_base.paymentterm",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_customer"], name="erp_base_pa_is_cust_c4e56c_idx"
                    ),
                    models.Index(
                        fields=["is_vendor"], name="erp_base_pa_is_vend_713b1e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "internal_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Internal reference / SKU",
                        max_length=100,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("description_sale", models.TextField(blank=True)),
                ("description_purchase", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("storable", "Storable Product"),
                            ("consumable", "Consumable"),
                            ("service", "Service"),
                        ],
                        default="storable",
                        max_length=15,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost / standard price",
                        max_digits=18,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("can_be_sold", models.BooleanField(default=True)),
                ("can_be_purchased", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="erp_base.productcategory",
                    ),
                ),
                (
                    "supplier_taxes",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"type_tax_use": "purchase"},
                        related_name="purchase_products",
                        to="erp_base.tax",
                    ),
                ),
                (
                    "taxes",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"type_tax_use": "sale"},
                        related_name="sale_products",
                        to="erp_base.tax",
                    ),
                ),
                (
                    "purchase_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_products",
                        to="erp_base.unitofmeasure",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="erp_base.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["active"], name="erp_base_pr_active_581be5_idx"
                    ),
                    models.Index(
                        fields=["product_type"], name="erp_base_pr_product_40cad8_idx"
                    ),
                ],
            },
        ),
    ]
