# Generated by Django 6.0.5 on 2026-07-18 12:48

import inventory_apps.erp_base.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=inventory_apps.erp_base.storage.TenantFileSystemStorage(), upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=inventory_apps.erp_base.storage.TenantFileSystemStorage(), upload_to='company/logos/'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=inventory_apps.erp_base.storage.TenantFileSystemStorage(), upload_to='products/'),
        ),
    ]
