# Generated by Django 6.0.5 on 2026-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0002_partner_image_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='available_in_pos',
            field=models.BooleanField(default=True),
        ),
    ]
