# Generated by Django 6.0.5 on 2026-07-23 13:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_base", "0003_producttemplate_available_in_pos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="Units of this currency per 1 unit of the company base currency",
                        max_digits=20,
                    ),
                ),
                ("rate_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="erp_base.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-rate_date"],
                "unique_together": {("currency", "rate_date")},
            },
        ),
    ]
