# Generated by Django 6.0.5 on 2026-07-26 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("erp_base", "0005_backfill_currency_rates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="invoice_policy",
            field=models.CharField(
                choices=[
                    ("order", "Ordered quantities"),
                    ("delivery", "Delivered quantities"),
                ],
                default="order",
                help_text="Invoice customers for the ordered or the delivered quantity.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=36)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("comment", "Message"),
                            ("tracking", "Field Change"),
                        ],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="erp_base_ac_content_e8ddfc_idx",
                    )
                ],
            },
        ),
    ]
