# Generated by Django 6.0.5 on 2026-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0007_alter_currencyrate_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='report_footer',
            field=models.TextField(blank=True, help_text="Extra line of text (e.g. registration number, bank details) shown under the contact line in every PDF's footer."),
        ),
        migrations.AddField(
            model_name='company',
            name='report_primary_color',
            field=models.CharField(default='#2D7A71', help_text='Hex color used for document titles, table totals, and links on PDFs (quotations, orders, invoices, reports).', max_length=7),
        ),
    ]
