# Generated by Django 6.0.5 on 2026-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0008_company_report_footer_company_report_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='report_layout',
            field=models.CharField(choices=[('standard', 'Light'), ('boxed', 'Boxed'), ('bold', 'Bold'), ('striped', 'Striped')], default='standard', help_text="Visual template used for every generated PDF (quotations, orders, invoices, reports) — mirrors Odoo's Light/Boxed/Bold/Striped document layouts.", max_length=20),
        ),
    ]
