# Generated by Django 6.0.5 on 2026-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0009_company_report_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='report_bank_account',
            field=models.CharField(blank=True, help_text='Bank account (e.g. IBAN) printed in the footer of invoices/bills for wire payment.', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='report_font',
            field=models.CharField(choices=[('Lato', 'Lato'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Oswald', 'Oswald'), ('Raleway', 'Raleway')], default='Lato', max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='report_paper_format',
            field=models.CharField(choices=[('a4', 'A4'), ('letter', 'US Letter')], default='a4', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='report_secondary_color',
            field=models.CharField(default='#1A1A1A', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='report_show_qr',
            field=models.BooleanField(default=False, help_text='Print a payment QR code on invoices (encodes the invoice reference and amount due).'),
        ),
        migrations.AddField(
            model_name='company',
            name='report_table_style',
            field=models.CharField(choices=[('standard', 'Light'), ('boxed', 'Boxed'), ('bold', 'Bold'), ('striped', 'Striped'), ('bubble', 'Bubble'), ('column', 'Column')], default='standard', help_text="Line-items table style — mirrors Odoo's Tables picker (Light/Boxed/Bold/Striped/Bubble/Column).", max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='report_tagline',
            field=models.CharField(blank=True, help_text='Short slogan printed under the company name in the PDF header, e.g. "Global Business Solutions".', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='report_layout',
            field=models.CharField(choices=[('standard', 'Light'), ('bubble', 'Bubble'), ('wave', 'Wave'), ('folder', 'Folder'), ('center', 'Center'), ('dual', 'Dual'), ('lines', 'Lines')], default='standard', help_text="Page/header template used for every generated PDF — mirrors Odoo's Layout picker (Light/Bubble/Wave/Folder/Center/Dual/Lines).", max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='report_primary_color',
            field=models.CharField(default='#2D7A71', help_text='Hex color used for document titles, table totals, and links on PDFs.', max_length=7),
        ),
    ]
