# Generated by Django 6.0.5 on 2026-09-05 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0010_company_report_bank_account_company_report_font_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('inventory', 'Inventory'), ('pos', 'Point of Sale'), ('accounting', 'Accounting'), ('contacts', 'Contacts'), ('reports', 'Reports')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
