# Generated by Django 6.0.5 on 2026-09-06 03:20

import django.db.models.deletion
import inventory_apps.erp_base.storage
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0011_tenantmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_type', models.CharField(choices=[('radio', 'Radio Buttons'), ('select', 'Dropdown'), ('color', 'Color Swatches')], default='radio', max_length=10)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('html_color', models.CharField(blank=True, help_text="Hex color for swatch display, e.g. #FF0000 (only used when the attribute's display type is Color)", max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='erp_base.productattribute')),
            ],
            options={
                'ordering': ['sequence', 'name'],
                'unique_together': {('attribute', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_reference', models.CharField(blank=True, help_text="Falls back to the template's reference if left blank", max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('price_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Added on top of the template's sales price for this combination", max_digits=18)),
                ('image', models.ImageField(blank=True, null=True, storage=inventory_apps.erp_base.storage.TenantFileSystemStorage(), upload_to='products/variants/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_values', models.ManyToManyField(related_name='variants', to='erp_base.productattributevalue')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='erp_base.producttemplate')),
            ],
            options={
                'ordering': ['product_template__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateAttributeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_lines', to='erp_base.productattribute')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lines', to='erp_base.producttemplate')),
                ('values', models.ManyToManyField(related_name='template_lines', to='erp_base.productattributevalue')),
            ],
            options={
                'ordering': ['attribute__sequence', 'attribute__name'],
                'unique_together': {('product_template', 'attribute')},
            },
        ),
    ]
