"""
erp_accounting/services.py — AccountingService: post journal entries, register payments,
reconcile, compute trial balance.
All posted moves must satisfy sum(debit) == sum(credit).
"""
from decimal import Decimal
from django.db import transaction
from django.utils import timezone


class AccountingService:

    @classmethod
    @transaction.atomic
    def post_move(cls, move):
        """Post a journal entry / invoice. Validates double-entry balance for journal entries."""
        from inventory_apps.erp_accounting.models import AccountMove, AccountMoveLine, AccountAccount

        if move.state == "posted":
            raise ValueError("Move is already posted")

        if move.move_type == "entry":
            # Pure journal entry: must balance
            lines = move.lines.all()
            total_debit = sum(l.debit for l in lines) or Decimal("0.00")
            total_credit = sum(l.credit for l in lines) or Decimal("0.00")
            if abs(total_debit - total_credit) > Decimal("0.01"):
                raise ValueError(
                    f"Journal entry does not balance: debit={total_debit}, credit={total_credit}"
                )
        else:
            # Invoice/Bill: build accounting lines automatically
            cls._generate_accounting_lines(move)

        move.state = "posted"
        if not move.name:
            from inventory_apps.erp_base.models import SequenceCounter
            prefix_map = {
                "out_invoice": "INV",
                "in_invoice": "BILL",
                "out_refund": "RINV",
                "in_refund": "RBILL",
                "entry": "JE",
            }
            move.name = SequenceCounter.next_sequence(prefix_map.get(move.move_type, "JE"))
        if not move.invoice_date:
            move.invoice_date = timezone.now().date()
        move.save(update_fields=["state", "name", "invoice_date"])
        move.compute_totals()
        return move

    @classmethod
    @transaction.atomic
    def recompute_journal_items(cls, move):
        """
        Re-run accounting-line generation for a move that's already posted.
        Needed for invoices/bills that were posted before a fix to
        `_generate_accounting_lines` — posting itself only ever runs once
        (post_move refuses to re-post), so an already-posted move whose
        lines were generated by older, buggy logic stays wrong forever
        unless something explicitly regenerates them. Safe to call more than
        once: it always fully rebuilds the generated lines from the current
        invoice-tab lines.
        """
        if move.move_type == "entry":
            raise ValueError("Journal entries don't have generated accounting lines to recompute")
        if move.state != "posted":
            raise ValueError("Only posted invoices/bills have journal items to recompute")
        cls._generate_accounting_lines(move)
        move.compute_totals()
        return move

    @classmethod
    def _generate_accounting_lines(cls, move):
        """
        Turn an invoice/bill into a genuine balanced double-entry journal entry.

        Previously this only ever created ONE counterpart (AR/AP) line with real
        debit/credit — the income/expense lines from the invoice tab kept
        debit=credit=0 forever (nothing else ever set them), and tax was never
        posted to a tax account at all. That meant the counterpart line didn't
        actually balance against anything, and the General Ledger/Trial Balance
        never reflected real invoice revenue or expense. Now:
          - each invoice-tab (product) line gets its debit/credit set from its
            own price_subtotal (income lines credit, expense lines debit;
            reversed for credit notes),
          - one aggregated tax line posts the total tax to a payable (sales)
            or receivable (purchase) tax account, if any tax was charged,
          - one counterpart line carries the tax-inclusive total on the
            receivable/payable account.
        Debits and credits are constructed to sum equal by design — see the
        sign table in the comments below.
        """
        from inventory_apps.erp_accounting.models import AccountAccount, AccountMoveLine

        is_customer_side = move.move_type in ("out_invoice", "out_refund")
        is_reversal = move.move_type in ("out_refund", "in_refund")

        # 1. Populate debit/credit on the existing invoice-tab lines.
        #    Customer invoice line (not a reversal): credit = subtotal (revenue).
        #    Vendor bill line (not a reversal): debit = subtotal (expense).
        #    A credit note reverses whichever side its own type would normally be.
        invoice_lines = list(move.lines.filter(exclude_from_invoice_tab=False))
        subtotal = Decimal("0.00")
        tax_total = Decimal("0.00")
        for line in invoice_lines:
            subtotal += line.price_subtotal
            tax_total += line.tax_amount
            if is_customer_side != is_reversal:
                debit, credit = Decimal("0.00"), line.price_subtotal
            else:
                debit, credit = line.price_subtotal, Decimal("0.00")
            AccountMoveLine.objects.filter(pk=line.pk).update(
                debit=debit, credit=credit, balance=debit - credit,
            )

        # Delete any previously-generated counterpart/tax lines so re-posting
        # (e.g. after editing) doesn't duplicate them.
        move.lines.filter(exclude_from_invoice_tab=True).delete()

        total = subtotal + tax_total
        if total == Decimal("0.00"):
            return

        counterpart_type = "asset_receivable" if is_customer_side else "liability_payable"
        counterpart_account = AccountAccount.objects.filter(
            account_type=counterpart_type, active=True
        ).first()
        if counterpart_account:
            if is_customer_side != is_reversal:
                cp_debit, cp_credit = total, Decimal("0.00")
            else:
                cp_debit, cp_credit = Decimal("0.00"), total
            AccountMoveLine.objects.create(
                move=move,
                account=counterpart_account,
                partner=move.partner,
                name=f"Counterpart: {move.partner.name if move.partner else ''}",
                debit=cp_debit,
                credit=cp_credit,
                exclude_from_invoice_tab=True,
                date_maturity=move.invoice_date_due,
            )

        # 2. Aggregated tax line: VAT Payable for sales, input VAT (receivable)
        #    for purchases — best-effort lookup by account type, since we don't
        #    track a dedicated "tax account" per Tax record yet.
        if tax_total != Decimal("0.00"):
            tax_account_type = "liability_current" if is_customer_side else "asset_current"
            tax_account = AccountAccount.objects.filter(
                account_type=tax_account_type, active=True
            ).first()
            if tax_account:
                if is_customer_side == is_reversal:
                    tax_debit, tax_credit = tax_total, Decimal("0.00")
                else:
                    tax_debit, tax_credit = Decimal("0.00"), tax_total
                AccountMoveLine.objects.create(
                    move=move,
                    account=tax_account,
                    name="Tax",
                    debit=tax_debit,
                    credit=tax_credit,
                    exclude_from_invoice_tab=True,
                )

    @classmethod
    @transaction.atomic
    def register_payment(cls, move, amount: Decimal, journal, date=None, memo: str = ""):
        """Register a payment against an invoice and partially/fully reconcile."""
        from inventory_apps.erp_accounting.models import AccountPayment, AccountMove, AccountMoveLine, AccountAccount

        if move.state != "posted":
            raise ValueError("Can only pay posted invoices")

        payment_type = "inbound" if move.move_type in ("out_invoice",) else "outbound"
        partner_type = "customer" if move.move_type in ("out_invoice",) else "supplier"

        payment = AccountPayment.objects.create(
            payment_type=payment_type,
            partner_type=partner_type,
            partner=move.partner,
            journal=journal,
            amount=amount,
            date=date or timezone.now().date(),
            memo=memo or move.name,
            reconcile_move=move,
            currency=move.currency,
        )

        # Create a payment journal entry
        if payment_type == "inbound":
            debit_account = journal.default_account
            credit_account = AccountAccount.objects.filter(
                account_type="asset_receivable", active=True
            ).first()
        else:
            debit_account = AccountAccount.objects.filter(
                account_type="liability_payable", active=True
            ).first()
            credit_account = journal.default_account

        if debit_account and credit_account:
            pay_move = AccountMove.objects.create(
                move_type="entry",
                journal=journal,
                partner=move.partner,
                date=payment.date,
                narration=memo,
                state="draft",
            )
            AccountMoveLine.objects.create(
                move=pay_move, account=debit_account, partner=move.partner,
                debit=amount, credit=Decimal("0.00"),
                name=f"Payment: {move.name}", exclude_from_invoice_tab=True,
            )
            AccountMoveLine.objects.create(
                move=pay_move, account=credit_account, partner=move.partner,
                debit=Decimal("0.00"), credit=amount,
                name=f"Payment: {move.name}", exclude_from_invoice_tab=True,
            )
            pay_move.state = "posted"
            pay_move.save(update_fields=["state"])
            payment.move = pay_move
            payment.save(update_fields=["move"])

        # Update invoice paid amount
        move.amount_paid = (move.amount_paid or Decimal("0.00")) + amount
        move.amount_residual = max(move.amount_total - move.amount_paid, Decimal("0.00"))
        if move.amount_residual <= Decimal("0.00"):
            move.payment_state = "paid"
        elif move.amount_paid > Decimal("0.00"):
            move.payment_state = "partial"
        move.save(update_fields=["amount_paid", "amount_residual", "payment_state"])
        payment.state = "reconciled"
        payment.save(update_fields=["state"])
        return payment

    @classmethod
    def post_payment(cls, payment):
        from inventory_apps.erp_accounting.models import AccountMove, AccountMoveLine, AccountAccount
        if payment.state != "draft":
            raise ValueError("Payment already posted")
        payment.state = "posted"
        if not payment.name:
            from inventory_apps.erp_base.models import SequenceCounter
            prefix = "PAY/IN" if payment.payment_type == "inbound" else "PAY/OUT"
            payment.name = SequenceCounter.next_sequence(prefix)
        payment.save(update_fields=["state", "name"])
        return payment

    @classmethod
    def get_trial_balance(cls, date_from=None, date_to=None):
        from inventory_apps.erp_accounting.models import AccountMove, AccountMoveLine, AccountAccount
        from django.db.models import Sum, Q

        qs = AccountMoveLine.objects.filter(move__state="posted")
        if date_from:
            qs = qs.filter(date__gte=date_from)
        if date_to:
            qs = qs.filter(date__lte=date_to)

        return (
            qs.values(
                "account__code",
                "account__name",
                "account__account_type",
            )
            .annotate(
                total_debit=Sum("debit"),
                total_credit=Sum("credit"),
            )
            .order_by("account__code")
        )

    @classmethod
    def get_profit_and_loss(cls, date_from=None, date_to=None):
        tb = cls.get_trial_balance(date_from, date_to)
        income = Decimal("0.00")
        expense = Decimal("0.00")
        lines = []
        for row in tb:
            at = row["account__account_type"]
            balance = (row["total_credit"] or Decimal("0.00")) - (
                row["total_debit"] or Decimal("0.00")
            )
            if at.startswith("income"):
                income += balance
                lines.append({**row, "balance": balance, "section": "income"})
            elif at.startswith("expense"):
                expense += abs(balance)
                lines.append({**row, "balance": balance, "section": "expense"})
        return {
            "lines": lines,
            "total_income": income,
            "total_expense": expense,
            "net_profit": income - expense,
        }
