# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "complete_name",
                    models.CharField(blank=True, editable=False, max_length=1000),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("supplier", "Vendor Location"),
                            ("view", "View"),
                            ("internal", "Internal Location"),
                            ("customer", "Customer Location"),
                            ("inventory", "Inventory Adjustments"),
                            ("production", "Production"),
                            ("transit", "Transit Location"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("is_scrap", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="erp_inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "ordering": ["complete_name"],
            },
        ),
        migrations.CreateModel(
            name="StockInventoryAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validate", "Validated"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="erp_inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("ref", models.CharField(blank=True, max_length=100)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("use_date", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "product")},
            },
        ),
        migrations.CreateModel(
            name="StockInventoryAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theoretical_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "inventory_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "difference_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_inventory.stockinventoryadjustment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_lines",
                        to="erp_base.producttemplate",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustment_lines",
                        to="erp_inventory.stocklot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPicking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("waiting", "Waiting Another Operation"),
                            ("confirmed", "Waiting"),
                            ("assigned", "Ready"),
                            ("done", "Done"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_done", models.DateTimeField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        help_text="Source document reference",
                        max_length=255,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickings_to",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "location_src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickings_from",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings",
                        to="erp_base.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "product_uom_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Demand quantity",
                        max_digits=18,
                    ),
                ),
                (
                    "quantity_done",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Actually done quantity",
                        max_digits=18,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("cancel", "Cancelled"),
                            ("waiting", "Waiting Another Move"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Available"),
                            ("done", "Done"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Unit cost at time of move",
                        max_digits=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_to",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "location_src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_from",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="erp_inventory.stocklot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="erp_base.producttemplate",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_lines",
                        to="erp_inventory.stockpicking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockPickingType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("incoming", "Receipt"),
                            ("outgoing", "Delivery"),
                            ("internal", "Internal Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sequence_prefix", models.CharField(default="WH/", max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_location_dest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_type_dest",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "default_location_src",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_type_src",
                        to="erp_inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "ordering": ["warehouse__name", "code"],
            },
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="picking_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickings",
                to="erp_inventory.stockpickingtype",
            ),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_name",
                    models.CharField(help_text="Short code (e.g. WH)", max_length=10),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="erp_base.company",
                    ),
                ),
                (
                    "lot_stock_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="lot_stock_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_stock",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "view_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="view_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_view",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "wh_input_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="wh_input_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_input",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "wh_output_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="wh_output_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_output",
                        to="erp_inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stockpickingtype",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picking_types",
                to="erp_inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="erp_inventory.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="StockQuant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "inventory_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quants",
                        to="erp_inventory.stocklot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name"],
                "unique_together": {("product", "location", "lot")},
            },
        ),
        migrations.CreateModel(
            name="ReorderingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "min_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "max_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "qty_multiple",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=18
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reordering_rules",
                        to="erp_base.producttemplate",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reordering_rules",
                        to="erp_inventory.stocklocation",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reordering_rules",
                        to="erp_inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name"],
                "unique_together": {("product", "location")},
            },
        ),
    ]
