# Generated by Django 6.0.5 on 2026-07-26 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockinventoryadjustment",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
