# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_accounting", "0001_initial"),
        ("erp_base", "0001_initial"),
        ("erp_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "New"),
                            ("cancel", "Cancelled"),
                            ("paid", "Paid"),
                            ("done", "Posted"),
                            ("invoiced", "Invoiced"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("date_order", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_return",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_order",
                        to="erp_accounting.accountmove",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_orders",
                        to="erp_base.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_order"],
            },
        ),
        migrations.CreateModel(
            name="POSOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=18
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "price_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "price_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "price_subtotal_incl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_pos.posorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_lines",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="POSPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_cash", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_payment_methods",
                        to="erp_accounting.accountjournal",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="POSConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("receipt_header", models.TextField(blank=True)),
                ("receipt_footer", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default sales journal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_configs",
                        to="erp_accounting.accountjournal",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_configs",
                        to="erp_inventory.warehouse",
                    ),
                ),
                (
                    "payment_methods",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configs",
                        to="erp_pos.pospaymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="POSSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new_session", "New Session"),
                            ("opening_control", "Opening Control"),
                            ("opened", "Open"),
                            ("closing_control", "Closing Control"),
                            ("closed", "Closed"),
                        ],
                        default="new_session",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_notes", models.TextField(blank=True)),
                ("closing_notes", models.TextField(blank=True)),
                (
                    "cash_register_balance_start",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "cash_register_balance_end",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "cash_register_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="erp_pos.posconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="POSPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pos_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="erp_pos.posorder",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_payments",
                        to="erp_pos.pospaymentmethod",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="erp_pos.possession",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddField(
            model_name="posorder",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="erp_pos.possession",
            ),
        ),
    ]
