# Generated by Django 6.0.5 on 2026-09-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderline',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text="When set, this line's taxes are removed from the order total."),
        ),
    ]
