# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_base", "0001_initial"),
        ("erp_purchase", "0001_initial"),
        ("erp_sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code_prefix_start", models.CharField(blank=True, max_length=20)),
                ("code_prefix_end", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["code_prefix_start"],
            },
        ),
        migrations.CreateModel(
            name="AccountAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset_cash", "Cash and Cash Equivalents"),
                            ("asset_receivable", "Receivable"),
                            ("asset_current", "Current Assets"),
                            ("asset_non_current", "Non-current Assets"),
                            ("asset_fixed", "Fixed Assets"),
                            ("asset_prepayments", "Prepayments"),
                            ("liability_payable", "Payable"),
                            ("liability_credit_card", "Credit Card"),
                            ("liability_current", "Current Liabilities"),
                            ("liability_non_current", "Non-current Liabilities"),
                            ("equity", "Equity"),
                            ("equity_unaffected", "Current Year Earnings"),
                            ("income", "Income"),
                            ("income_other", "Other Income"),
                            ("expense", "Expense"),
                            ("expense_depreciation", "Depreciation"),
                            ("expense_direct_cost", "Cost of Revenue"),
                            ("off_balance", "Off-Balance Sheet"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reconcile",
                    models.BooleanField(
                        default=False,
                        help_text="Allow reconciliation (for AR/AP accounts)",
                    ),
                ),
                ("deprecated", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="erp_accounting.accountgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("code",)},
            },
        ),
        migrations.CreateModel(
            name="AccountJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sales"),
                            ("purchase", "Purchase"),
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("general", "Miscellaneous"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sequence_prefix", models.CharField(blank=True, max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journals",
                        to="erp_base.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journals",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_default",
                        to="erp_accounting.accountaccount",
                    ),
                ),
                (
                    "suspense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_suspense",
                        to="erp_accounting.accountaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountMove",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=100)),
                ("ref", models.CharField(blank=True, max_length=255)),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("entry", "Journal Entry"),
                            ("out_invoice", "Customer Invoice"),
                            ("out_refund", "Customer Credit Note"),
                            ("in_invoice", "Vendor Bill"),
                            ("in_refund", "Vendor Credit Note"),
                        ],
                        default="entry",
                        max_length=15,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            ("not_paid", "Not Paid"),
                            ("in_payment", "In Payment"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("reversed", "Reversed"),
                        ],
                        default="not_paid",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("invoice_date_due", models.DateField(blank=True, null=True)),
                ("invoice_origin", models.CharField(blank=True, max_length=255)),
                ("narration", models.TextField(blank=True)),
                (
                    "amount_untaxed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_residual",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_moves",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="erp_accounting.accountjournal",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_moves",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="erp_purchase.purchaseorder",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="erp_sales.saleorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountMoveLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=10)),
                ("name", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField(blank=True, null=True)),
                ("date_maturity", models.DateField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=18
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "price_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "amount_residual",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("reconciled", models.BooleanField(default=False)),
                ("exclude_from_invoice_tab", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="move_lines",
                        to="erp_accounting.accountaccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="move_lines",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_accounting.accountmove",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="move_lines",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="move_lines",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("outbound", "Send Money"),
                            ("inbound", "Receive Money"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[("customer", "Customer"), ("supplier", "Vendor")],
                        default="customer",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Validated"),
                            ("sent", "Sent"),
                            ("reconciled", "Reconciled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="erp_accounting.accountjournal",
                    ),
                ),
                (
                    "move",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_record",
                        to="erp_accounting.accountmove",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "reconcile_move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="erp_accounting.accountmove",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="accountmove",
            index=models.Index(
                fields=["move_type", "state"], name="erp_account_move_ty_a7f88d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountmove",
            index=models.Index(
                fields=["payment_state"], name="erp_account_payment_964732_idx"
            ),
        ),
    ]
