# Generated by Django 6.0.5 on 2026-07-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_accounting", "0002_alter_accountmove_date_alter_accountpayment_date"),
        ("erp_base", "0007_alter_currencyrate_rate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmoveline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="account_move_lines", to="erp_base.tax"
            ),
        ),
    ]
