# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "RFQ"),
                            ("sent", "RFQ Sent"),
                            ("purchase", "Purchase Order"),
                            ("done", "Locked"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("date_order", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_planned", models.DateTimeField(blank=True, null=True)),
                ("date_approve", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "amount_untaxed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("receipt_count", models.PositiveIntegerField(default=0)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="erp_base.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="erp_base.paymentterm",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_order"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "product_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=18
                    ),
                ),
                (
                    "qty_received",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "qty_billed",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "price_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                ("date_planned", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_purchase.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
    ]
