# Generated by Django 6.0.5 on 2026-07-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='partner_ref',
            field=models.CharField(blank=True, help_text="Vendor's own quote/order reference", max_length=255),
        ),
    ]
