# Generated by Django 6.0.5 on 2026-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_base", "0007_alter_currencyrate_rate_date"),
        ("erp_purchase", "0002_purchaseorder_partner_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="purchase_order_lines", to="erp_base.tax"
            ),
        ),
    ]
