# Generated by Django 6.0.5 on 2026-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_purchase", "0003_purchaseorderline_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
