# Generated by Django 6.0.5 on 2026-09-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_base', '0013_backfill_default_variants'),
        ('erp_purchase', '0007_finalize_variant_fk_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='product_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='erp_base.unitofmeasure'),
        ),
    ]
