# Generated by Django 6.0.5 on 2026-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_waitlistsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
