# Generated by Django 6.0.5 on 2026-07-09 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_base", "0001_initial"),
        ("erp_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Quotation"),
                            ("sent", "Quotation Sent"),
                            ("sale", "Sales Order"),
                            ("done", "Locked"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("date_order", models.DateTimeField(default=django.utils.timezone.now)),
                ("validity_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("client_order_ref", models.CharField(blank=True, max_length=100)),
                (
                    "amount_untaxed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("delivery_count", models.PositiveIntegerField(default=0)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="erp_base.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_orders",
                        to="erp_base.currency",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_orders",
                        to="erp_base.partner",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="erp_base.paymentterm",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="erp_inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_order"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "product_uom_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Ordered quantity",
                        max_digits=18,
                    ),
                ),
                (
                    "qty_delivered",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "qty_invoiced",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "price_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp_sales.saleorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="erp_base.producttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(fields=["state"], name="erp_sales_s_state_0075f0_idx"),
        ),
    ]
