# Generated by Django 6.0.5 on 2026-08-20 16:09

import inventory_apps.authentication.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_cross_schema_fk_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Drawn or uploaded signature image, used on documents (quotations, invoices, etc.)', null=True, storage=inventory_apps.authentication.storage.TenantFileSystemStorage(), upload_to='signatures/'),
        ),
    ]
